---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-json
          - id: check-yaml
          - id: check-toml
          - id: check-xml
          - id: check-merge-conflict
          - id: check-docstring-first
          - id: debug-statements
  # formatters
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
            exclude: README.md
            additional_dependencies: [black==22.6.0]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            files: \.(py)$
            args: [--settings-path=pyproject.toml, --profile, black]
  # linters
    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear
                - flake8-comprehensions
                - flake8-simplify
            exclude: src/tests
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-use-type-annotations
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-check-blanket-type-ignore
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-check-blanket-noqa

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-no-eval
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-no-log-warn
    - repo: https://github.com/guilatrova/tryceratops
      rev: v1.1.0
      hooks:
          - id: tryceratops
  # typing
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.971
      hooks:
          - id: mypy
            files: src/silex
            args: [--explicit-package-bases, --namespace-packages, --ignore-missing-imports, --show-error-codes]
  # security
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.4
      hooks:
          - id: bandit
            files: src/silex
    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: v1.3.0
      hooks:
          - id: python-safety-dependencies-check
