---
name: Release

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.cache/pypoetry/virtualenvs
                  key: ubuntu-latest-poetry-${{ hashFiles('poetry.lock') }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install poetry
                  poetry config virtualenvs.create false
                  poetry install
            - name: Python Semantic Release
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "action@github.com"
                  semantic-release publish -D commit_author="github-actions <action@github.com>"
              env:
                  GH_TOKEN: ${{secrets.SEMANTIC_RELEASE_GH_TOKEN}}
                  PYPI_TOKEN: ${{secrets.PYPI_TOKEN}}
